version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse-web:
    image: concourse/concourse:3.14.1
    command: web
    links:
     - nginx
     - concourse-db
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=https://192.168.64.155:8080
    - CONCOURSE_BASIC_AUTH_USERNAME=concourse
    - CONCOURSE_BASIC_AUTH_PASSWORD=concourse
    - CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH

  concourse-worker:
    image: concourse/concourse:3.14.1
    command: worker
    privileged: true
    links:
     - concourse-web
     - nginx
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
    - CONCOURSE_GARDEN_DNS_SERVER=192.168.64.10
      #- http_proxy_url=http://proxy.vmware.com:3128
      #- https_proxy_url=http://proxy.vmware.com:3128
      #- no_proxy=localhost,127.0.0.1,192.168.110.11,8.8.8.8,10.193.99.2,192.168.110.10
      #- HTTP_PROXY==http://proxy.vmware.com:3128
      #- HTTPS_PROXY==http://proxy.vmware.com:3128
      #- NO_PROXY=localhost,127.0.0.1,192.168.110.11,8.8.8.8,10.193.99.2,192.168.110.10

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
     - /root/nsxt/:/var/www/html/
    #- ./nginx/conf.d:/etc/nginx/conf.d
    #- ./nginx/vhost.d:/etc/nginx/vhost.d
     - /root/nsxt/:/usr/share/nginx/html
    #- ./nginx/certs:/etc/nginx/certs:ro
    #- ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
     - "80:80"
     - "443:443"
